### ISSUE TITLE
Bot doesnt delete temp channels - Error

### ISSUE THREAD

**Issue by zorrigas** [sync667/UseTS-AdminBOT#21]
SinusBot 0.9.15-b20cc30
UseTS-AdminBOT 0.4.2

```
2016-12-04T15:16:17-03:00 TypeError: Cannot access member 'clients' of undefined at getClientsNumber (UseTSAdminBOT.js:942:29) at UseTSAdminBOT.js:512:25
2016-12-04T15:16:17-03:00 Could not get channel: HTTP returned an error: Error; Code: 500; Message: Error
2016-12-04T15:16:17-03:00 Error on call #5
```

**Comment by sync667** [comment]
Yes i will correct this soon.
